### ISSUE TITLE
Upgrade project to MapR 6.0.1

### ISSUE THREAD

**Issue by raman-nbg** [mapr-demos/mapr-streams-sample-programs#3]
I am using the MapR Sandbox in version 6.0.1. It would be nice to update this sample to the latest MapR version.

I am using mapr-streams in version `6.0.1-mapr` and Kafka-clients in version `1.0.1-mapr-streams-6.0.1` for the latest MapR version.

**Comment by conorbmurphy** [comment]
Same here.  I'm running into problems on the latest MapR sandbox

**Comment by alivcor** [comment]
Can replicate the same issue as reported [here](https://mapr.com/community/s/question/0D50L00006BIsvZSAT/problem-consuming-records-from-maprstream-using-sparkstreaming-api)


We have tried following combinations versions and all fail with same error:

```
<properties>
        <mapr-version>6.1.0-mapr</mapr-version> // and 6.0.0-mapr
        <mapr-streams-version>1.1.1-mapr-streams-6.1.0</mapr-streams-version> // and 1.0.1-mapr-1808-streams-6.1.0,   0.9.0.0-mapr-1808-streams-6.1.0,   0.9.0.0-mapr-1801-streams-6.1.0,   0.9.0.0-mapr-1801-streams-6.0.0
</properties>
```
<pre>
|~/mapr-streams-sample-programs - [master !?]$ java -cp `mapr classpath`:./target/mapr-streams-examples-1.0-SNAPSHOT-jar-with-dependencies.jar com.mapr.examples.Run producer
</pre>


```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/mapr/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/user/mapr-streams-sample-programs/target/mapr-streams-examples-1.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
org.apache.kafka.clients.mapr.GenericHFactory.getImplementorInstance
```

**Comment by sanejkom** [comment]
Hi, I know this is the old issue but I managed to make the example run.

I've set below versions in `pom.xml`
```
<properties>
        <mapr-version>6.1.0-mapr</mapr-version>
        <mapr-streams-version>1.1.1-mapr-streams-6.1.0</mapr-streams-version>
</properties>
```

Later I've run mvn compile and mvc package, compied a new jar file into the claster and run it like in the guide.
It still shows the Slf4j warnings but at least it works

![image](https://user-images.githubusercontent.com/10105840/89883785-f0e98780-dbc8-11ea-94e8-b318ee77b522.png)


I hope it helps someone 😄

**Comment by tdunning** [comment]
Excellent!

**Comment by tdunning** [comment]
Adopted this suggestion
